server:
  port: 9000

# 前端应用的URL配置
spa:
  frontend-url: http://localhost:8081

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务ID转小写
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:8080"
              - "http://localhost:8081"
              - "http://127.0.0.1:8080"
              - "http://127.0.0.1:8081"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        # 业务微服务路由 - 最高优先级
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**,/food/**,/foodCategory/**
          filters:
            - StripPrefix=0
          order: 1
          
        # 用户微服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/deliveryAddress/**
          filters:
            - StripPrefix=0
          order: 2
          
        # 订单微服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**,/cart/**
          filters:
            - StripPrefix=0
          order: 3
          
        # 前端路由刷新处理 - 最低优先级
        - id: frontend-fallback
          uri: ${spa.frontend-url}
          predicates:
            - Path=/**
          filters:
            # 简单重定向，无需尝试保留路径
            - RedirectTo=302,${spa.frontend-url}
          order: 100
          
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway 