server:
  port: 9000

# 前端应用的URL配置
spa:
  frontend-url: http://localhost:8081

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务ID转小写
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:8080"
              - "http://localhost:8081"
              - "http://127.0.0.1:8080"
              - "http://127.0.0.1:8081"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        # 业务微服务路由 - 最高优先级
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=0
          order: 1
          
        # 食品微服务路由
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/food/**,/foodCategory/**
          filters:
            - StripPrefix=0
          order: 2
          
        # 用户微服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
          order: 3
          
        # 地址微服务路由
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/deliveryAddress/**
          filters:
            - StripPrefix=0
          order: 4
          
        # 订单微服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=0
          order: 5
          
        # 购物车微服务路由
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=0
          order: 6
          
        # 消费者服务路由
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=0
          order: 7
          
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: gateway 