server:
  port: 8889

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cangkui6/config-repo_finalProject.git
          default-label: master
          clone-on-start: true
          timeout: 10
          # 如果是私有仓库，需要配置用户名和密码
          # username: your-github-username
          # password: your-github-token
        # 启用健康检查
        health:
          repositories:
            enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    # 启用健康检查
    healthcheck:
      enabled: true
    # 配置获取服务列表的间隔时间
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 配置心跳间隔
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    # 启用健康检查
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh,refresh
  endpoint:
    health:
      show-details: always 