server:
  port: 8889

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cangkui6/config-repo_finalProject.git
          default-label: master
          clone-on-start: true
          timeout: 10
          # 如果是私有仓库，需要配置用户名和密码
          # username: your-github-username
          # password: your-github-token
        # 启用健康检查
        health:
          repositories:
            enabled: true
    # 消息总线配置
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      id: config-server-8889
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    # 启用健康检查
    healthcheck:
      enabled: true
    # 配置获取服务列表的间隔时间
    registry-fetch-interval-seconds: 30
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 配置心跳间隔
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    # 启用健康检查
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
    bus-refresh:
      enabled: true
  health:
    rabbit:
      enabled: true

# 日志配置
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.bus: DEBUG
    org.springframework.amqp: DEBUG
    com.elm.config: INFO 