server:
  port: 8006

spring:
  application:
    name: address-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8
    username: root
    password: 2254600749@qq.com
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.elm.common.entity
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

feign:
  circuitbreaker:
    enabled: true

# Resilience4j 配置
resilience4j:
  circuitbreaker:
    instances:
      deliveryAddressService:
        # 故障率閾值，當故障率達到50%時觸發熔斷
        failure-rate-threshold: 50
        # 慢調用率閾值，當慢調用率達到80%時觸發熔斷
        slow-call-rate-threshold: 80
        # 慢調用時間閾值，超過2秒視為慢調用
        slow-call-duration-threshold: 2s
        # 最小調用次數，只有達到此次數才會計算故障率
        minimum-number-of-calls: 5
        # 滑動視窗類型：COUNT_BASED（基於計數）或TIME_BASED（基於時間）
        sliding-window-type: COUNT_BASED
        # 滑動視窗大小
        sliding-window-size: 10
        # 半開狀態下的測試調用次數
        permitted-number-of-calls-in-half-open-state: 3
        # 熔斷器開啟狀態持續時間
        wait-duration-in-open-state: 10s
        # 是否自動從開啟狀態轉換到半開狀態
        automatic-transition-from-open-to-half-open-enabled: true
        # 記錄異常
        record-exceptions:
          - java.lang.Exception
        # 忽略異常
        ignore-exceptions:
          - java.lang.IllegalArgumentException
  
  # 重試配置
  retry:
    instances:
      deliveryAddressService:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.lang.Exception
        ignore-exceptions:
          - java.lang.IllegalArgumentException
  
  # 限流配置
  ratelimiter:
    instances:
      deliveryAddressService:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 3s

# 監控端點
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always 